[package]
name = "dating_app"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }